version: '3'
services:
  rls-gateway:
    image:  rls-gateway
    container_name: rls-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_LOG_LEVEL=debug
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PLUGINS=bundled,rls-auth
      - KONG_NGINX_PROXY_GZIP=on
      - KONG_NGINX_PROXY_GZIP_TYPES="text/plain application/json"
      - KONG_DECLARATIVE_CONFIG=/usr/local/share/kong.yml
      - PING_URL= # REPLACE THIS
      - PING_RESPONSE_TIMEOUT=3000 #timeout in ms
      - PING_RATE_LIMIT_PER_SEC=10
      - PING_RATE_LIMIT_PER_MIN=100
      - PING_RATE_LIMIT_POLICY=local #local/redis/cluster
      - AUTH_URL= # REPLACE THIS
      - AUTH_TIMEOUT=1 #timeout in sec
      - META_URL= # REPLACE THIS
      - META_RESPONSE_TIMEOUT=3000 #timeout in ms
      - HISTORY_URL= # REPLACE THIS
      - HISTORY_RESPONSE_TIMEOUT=3000 #timeout in ms
      - AUTH_SERVICE_URL= # REPLACE THIS
      - AUTH_RESPONSE_TIMEOUT=3000 #timeout in ms
      - AUTH_CACHE_TTL=3 # ttl in sec
    ports:
      - "80:8000"
      - "443:8443"
